# Importing EHS data

## Setup

In [3]:
import pandas as pd
import os

In [2]:
ehs_dir=r'C:\Users\cvskf\OneDrive - Loughborough University\_Data\English_Housing_Survey_2016_Housing_Stock_Data\UKDA-8350-tab\tab'

## Read data

In [7]:
df=pd.read_csv(
    os.path.join(ehs_dir,'physical_15plus16_eul.tab'),
    sep='\t'
)
df

,serialanon,dwtypenx,dwtype8x,dwtype3x,housex,dwage7x,dwage6x,dwage5x,dwage4x,alltypex,...,dhreasny,dhreasnz,dhtcreasy,cstactux,cstactbx,cstactcx,cststdux,cststdbx,cststdcx,dhcosty
0,15160010001,3,3,1,1,4,4,4,4,10,...,1,1,-9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,436.176447
1,15160010005,7,7,2,2,4,4,4,4,2,...,-9,-9,-9,2469.623198,2469.623198,2469.623198,46.975457,46.975457,46.975457,-9.000000
2,15160010007,8,8,3,2,4,4,4,4,1,...,-9,-9,-9,1210.162655,1982.907940,1982.907940,20.153443,33.148276,33.148276,-9.000000
3,15160010010,5,5,1,1,4,4,4,4,4,...,-9,-9,-9,134.405098,134.405098,134.405098,1.806477,1.806477,1.806477,-9.000000
4,15160010011,1,1,1,1,5,5,5,4,10,...,-9,-9,-9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12287,16170038015,4,4,1,1,2,2,2,2,6,...,-9,-9,-9,328.320608,2466.821204,3340.084005,1.693010,10.156121,10.156121,-9.000000
12288,16170038016,2,2,1,1,1,1,1,1,7,...,1,1,-9,2517.203965,2704.312827,5232.150740,31.787400,34.467133,71.855308,62.060654
12289,16170038017,3,3,1,1,3,3,3,3,9,...,-9,-9,-9,0.000000,713.625006,1006.982943,0.000000,4.686249,4.686249,-9.000000
12290,16170038019,7,7,2,2,1,1,1,1,2,...,-9,-9,-9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.000000
12291,16170038028,5,5,1,1,2,2,2,2,4,...,1,1,-9,604.630030,5540.967244,42357.325002,5.105817,56.089742,500.000000,46213.803897

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12292 entries, 0 to 12291
Data columns (total 70 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   serialanon  12292 non-null  int64
 1   dwtypenx    12292 non-null  int64
 2   dwtype8x    12292 non-null  int64
 3   dwtype3x    12292 non-null  int64
 4   housex      12292 non-null  int64
 5   dwage7x     12292 non-null  int64
 6   dwage6x     12292 non-null  int64
 7   dwage5x     12292 non-null  int64
 8   dwage4x     12292 non-null  int64
 9   alltypex    12292 non-null  int64
 10  floorx      12292 non-null  float64
 11  floor5x     12292 non-null  int64
 12  floory      12292 non-null  float64
 13  floor5y     12292 non-null  int64
 14  storeyx     12292 non-null  int64
 15  dblglaz2    12292 non-null  int64
 16  dblglaz4    12292 non-null  int64
 17  secure      12292 non-null  int64
 18  parking     12292 non-null  int64
 19  neivisx     12292 non-null  int64
 20  dampalf     12292 non-null  int64
 21  dampcdf     12292 non-null  int64
 22  damppnf     12292 non-null  int64
 23  damprsf     12292 non-null  int64
 24  lv1upkpx    12292 non-null  int64
 25  lv2trafx    12292 non-null  int64
 26  lv3utilx    12292 non-null  int64
 27  lvnumx      12292 non-null  int64
 28  lvanyx      12292 non-null  int64
 29  attic       12292 non-null  int64
 30  heat4x      12292 non-null  int64
 31  heat7x      12292 non-null  int64
 32  sysage      12292 non-null  int64
 33  fuelx       12292 non-null  int64
 34  watersys    12292 non-null  int64
 35  boiler      12292 non-null  int64
 36  loftinsx    12292 non-null  int64
 37  loftins4    12292 non-null  int64
 38  loftins6    12292 non-null  int64
 39  loftinsu    12292 non-null  int64
 40  loftu4      12292 non-null  int64
 41  wallinsz    12292 non-null  int64
 42  wallcavy    12292 non-null  int64
 43  pcavwallx   12292 non-null  int64
 44  wins95x     12292 non-null  int64
 45  sap12       12292 non-null  float64
 46  sap412      12292 non-null  int64
 47  rdsap09     12292 non-null  float64
 48  EPceeb12e   12292 non-null  int64
 49  EPceir12e   12292 non-null  float64
 50  EPceib12e   12292 non-null  int64
 51  dhomesz     12292 non-null  int64
 52  dhomesy     12292 non-null  int64
 53  dhhhsrsx    12292 non-null  int64
 54  dhhhsrsy    12292 non-null  int64
 55  dhthermy    12292 non-null  int64
 56  dhdisrx     12292 non-null  int64
 57  dhmodx      12292 non-null  int64
 58  dhnumy      12292 non-null  int64
 59  dhnumz      12292 non-null  int64
 60  dhreasny    12292 non-null  int64
 61  dhreasnz    12292 non-null  int64
 62  dhtcreasy   12292 non-null  int64
 63  cstactux    12292 non-null  float64
 64  cstactbx    12292 non-null  float64
 65  cstactcx    12292 non-null  float64
 66  cststdux    12292 non-null  float64
 67  cststdbx    12292 non-null  float64
 68  cststdcx    12292 non-null  float64
 69  dhcosty     12292 non-null  float64
dtypes: float64(12), int64(58)
memory usage: 6.6 MB

In [9]:
df.columns

Index(['serialanon', 'dwtypenx', 'dwtype8x', 'dwtype3x', 'housex', 'dwage7x',
       'dwage6x', 'dwage5x', 'dwage4x', 'alltypex', 'floorx', 'floor5x',
       'floory', 'floor5y', 'storeyx', 'dblglaz2', 'dblglaz4', 'secure',
       'parking', 'neivisx', 'dampalf', 'dampcdf', 'damppnf', 'damprsf',
       'lv1upkpx', 'lv2trafx', 'lv3utilx', 'lvnumx', 'lvanyx', 'attic',
       'heat4x', 'heat7x', 'sysage', 'fuelx', 'watersys', 'boiler', 'loftinsx',
       'loftins4', 'loftins6', 'loftinsu', 'loftu4', 'wallinsz', 'wallcavy',
       'pcavwallx', 'wins95x', 'sap12', 'sap412', 'rdsap09', 'EPceeb12e',
       'EPceir12e', 'EPceib12e', 'dhomesz', 'dhomesy', 'dhhhsrsx', 'dhhhsrsy',
       'dhthermy', 'dhdisrx', 'dhmodx', 'dhnumy', 'dhnumz', 'dhreasny',
       'dhreasnz', 'dhtcreasy', 'cstactux', 'cstactbx', 'cstactcx', 'cststdux',
       'cststdbx', 'cststdcx', 'dhcosty'],
      dtype='object')